rest:
  ssl: true
  host: demo.dspace.org
  port: 443
  nameSpace: /server

info:
  # Whether the end user agreement is required before users may use the repository.
  # If enabled, the user will be required to accept the agreement before they can use the repository.
  # If disabled, the page will not exist and no agreement is required to use the repository
  enableEndUserAgreement: false
  # Whether the privacy statement should exist or not.
  enablePrivacyStatement: false

# Whether to enable Markdown (https://commonmark.org/) and MathJax (https://www.mathjax.org/)
# display in supported metadata fields. By default, only dc.description.abstract is supported.
markdown:
  enabled: true
  mathjax: true

# Whether to enable media viewer for image and/or video Bitstreams (i.e. Bitstreams whose MIME type starts with 'image' or 'video').
# When "image: true", this enables a gallery viewer where you can zoom or page through images.
# When "video: true", this enables embedded video streaming.  This embedded video streamer also supports audio files.
mediaViewer:
  image: true
  video: true

themes:
  # Specific Item
  # - name: etdr
  #   extends: krex
  #   handle: '2097/43295'

  - name: etdr
    extends: krex
    # handle: '2097/4'
    uuid: '6d684812-6d29-4564-8b51-f5670957936b'

  - name: etdr
    extends: krex
    # handle: '2097/4234'
    uuid: 'c786bb54-ccbc-435c-b310-d41465c3eede'

  - name: etdr
    extends: krex
    # handle: '2097/1064'
    uuid: 'd7856439-3d4d-43ea-8016-89bfed705f47'

  - name: etdr
    extends: krex
    # handle: '2097/39169'
    uuid: '6f9a9785-2a0f-4e15-ac59-947ee95ed896'

  # default theme, based on DSpace
  - name: krex
    headTags:
      # Insert <link rel="icon" href="assets/krex/images/favicons/favicon.ico" sizes="any"/> into the <head> of the page.
      - tagName: link
        attributes:
          rel: icon
          href: assets/krex/images/favicons/favicon.ico
          sizes: any
