# DSpace Docker image build for hub.docker.com
name: Docker images

# Run this Build for all pushes to 'main' or maintenance branches, or tagged releases.
# Also run for PRs to ensure PR doesn't break Docker build process
# NOTE: uses "reusable-docker-build.yml" in kstatelibrariesit/kstatelibrariesit to
# actually build each of the Docker images
# https://github.com/kstatelibrariesit/kstatelibrariesit/blob/main/.github/workflows/reusable-docker-build.yml
#
on:
  push:
    branches:
      - 'ksul_dspace-**'
    tags:
      - 'ksul_dspace-**'
  pull_request:

permissions:
  contents: read  #  to fetch code (actions/checkout)

jobs:
  #############################################################
  # Build/Push the 'dspace/dspace-angular' image
  #############################################################
  krex-dspace-angular:
    # Ensure this job never runs on forked repos. It's only executed for 'kstatelibrariesit/dspace-angular'
    if: github.repository == 'kstatelibrariesit/dspace-angular'
    # Use the reusable-docker-build.yml script from DSpace/DSpace repo to build our Docker image
    uses: kstatelibrariesit/kstatelibrariesit/.github/workflows/reusable-docker-build.yml@main
    with:
      build_id: dspace-dspace-angular-dev
      image_name: kstatelibraries/krex-dspace-angular
      dockerfile_path: ./Dockerfile
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}

  #############################################################
  # Build/Push the 'kstatelibrariesit/krex-dspace-angular' image ('-dist' tag)
  #############################################################
  krex-dspace-angular-dist:
    # Ensure this job never runs on forked repos. It's only executed for 'kstatelibrariesit/dspace-angular'
    if: github.repository == 'kstatelibrariesit/dspace-angular'
    # Use the reusable-docker-build.yml script from DSpace/DSpace repo to build our Docker image
    uses: kstatelibrariesit/kstatelibrariesit/.github/workflows/reusable-docker-build.yml@main
    with:
      build_id: krex-dspace-angular-dist
      image_name: kstatelibraries/krex-dspace-angular
      dockerfile_path: ./Dockerfile.dist
      # As this is a "dist" image, its tags are all suffixed with "-dist". Otherwise, it uses the same
      # tagging logic as the primary 'kstatelibraries/krex-dspace-angular' image above.
      tags_flavor: suffix=-dist
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}

